spring.application.name=eureka

server.port=8761

eureka.client.register-with-eureka=false
<!-- en produccion el fetch registry debe estar en true -->
eureka.client.fetch-registry=false
eureka.instance.prefer-ip-address=true